@startuml
scale 2
class Source {
    - name : String
    - start_collect : Data
    - end_collect : Data
    - input_file : String
    - type : String

    + process() : None

}
note bottom : process() : structure if/elif/else

note "type : survey, census, webscrapping, administrative" as N 
N.Source



@enduml