@startuml
scale 2
abstract class AbstractSource << abstract >> {
    - name : String
    - start_collect : Date
    - end_collect : Date
    - input_file : String

    - common_process()
    # {abstract} custom_process()
    + process()


}

class Survey {
    # custom_process()
}

class Census {
    # custom_process()
}

class Webscrapping {
    # custom_process()
}

class AdministrativeFile {
    #  custom_process()
}

AbstractSource <|-- Survey
AbstractSource <|-- Census
AbstractSource <|-- Webscrapping
AbstractSource <|-- AdministrativeFile

@enduml