@startuml
scale 2
class Source {
    - name : String
    - start_collect : Date
    - end_collect : Date
    - input_file : String

    - common_process()
    # custom_process()
    + process()


}
note left : custom_process() : pass


class Survey {
    # custom_process()

}

class Census {
    # custom_process()

}

class Webscrapping {
    # custom_process()

}

class AdministrativeFile {
    # custom_process()

}

Source <|-- Survey
Source <|-- Census
Source <|-- Webscrapping
Source <|-- AdministrativeFile

@enduml