@startuml
scale 1.5
abstract class  AbstractPersonnage <<abstract>> {
    #_name : String
	#_phrase_attaque : String 
	#_phrase_defense : String 
	+degat_attaque() float
}

abstract class AbstractEquipement {
	#_nom String
	 }
	 
class Statistique {
	 -__force : int
	 -__agilite : int
	 -__magie : int
	 -__defense : int
	 -__points_de_vie  : int
}

AbstractPersonnage *-left-"1" Statistique
AbstractEquipement *--"1" Statistique

@enduml