@startuml
scale 1.5
abstract class  AbstractPersonnage <<abstract>> {
    #_nom  : String
    #_phrase_attaque : String
    #_phrase_defense : String
    #_force : int
    #_agilite : int
    #_magie : int
    #_defense : int
    #_points_de_vie : int
    +degats_attaque() float    
    }

abstract class  AbstractEquipement <<abstract>> {
    #_nom  : String
    #_force : int
    #_agilite : int
    #_magie : int
    #_defense : int
    #_points_de_vie : int
    }
@enduml