@startuml
scale 1.5
abstract class AbstractPersonnage 	<<abstract>> {
	#_phrase_attaque : String 
	#_phrase_defense : String 
	+degats_attaque() float
    }
	 

abstract class AbstractEquipement <<abstract>> {
	#_nom : String
}
	 
class Statistique {
	 -__force : int
	 -__agilite : int
	 -__magie : int
	 -__defense : int
	 -__points_de_vie : int
}

abstract class AbstractArme <<abstract>>{
    #_description_utilisation : String
    #_base_attaque : int
    +utiliser_arme(Statistique) float
}


abstract class AbstractArmure <<abstract>>{
    #_description_defense : String 
    #_base_defense : int
    +utiliser_armure(Statistique, float) float 
}
	 	
AbstractPersonnage *-up-"1" Statistique
AbstractArme "0..1"<-- AbstractPersonnage
AbstractEquipement <|-- AbstractArme
AbstractEquipement *--"1" Statistique

AbstractPersonnage <|--  Magicien
AbstractPersonnage <|--  Guerrier
AbstractPersonnage <|--  Voleur

Epee --|> AbstractArme
Baton --|> AbstractArme
Arc --|> AbstractArme
AbstractArme <|-- Couteau
AbstractArme <|-- Lance
AbstractArme <|-- Livre
AbstractArmure <|-- Robe
AbstractArmure <|-- ArmureLegere
AbstractArmure <|-- ArmureLourde
AbstractArmure "0..1" <-- AbstractPersonnage
AbstractEquipement <|-- AbstractArmure
@enduml