@startuml
scale 1.5

class Personnage {
	#_nom : String
	#_phrase_attaque : String
	#_phrase_defense : String
	+degats_attaque() float    
	}

class PersonnagesService {
	+attaque() String
}

class Magicien {
	#_nom : String
	#_phrase_attaque : String
	#_phrase_defense : String
	+degats_attaque() float    
}

class Guerrier {
	#_nom : String
	#_phrase_attaque : String
	#_phrase_defense : String
	+degats_attaque() float    
}

class Voleur {
	#_nom : String
	#_phrase_attaque : String
	#_phrase_defense : String
	+degats_attaque() float    
}

PersonnagesService ..> Personnage : <<use>>
Personnage <|-- Magicien
Personnage <|-- Guerrier
Personnage <|-- Voleur
@enduml