@startuml
scale 1.5

class Personnage {
    -__nom : String
	-__personnage_type : String
	+get_personnage_type() String
}
	
class PersonnagesService {
	+attaque() String
}
	
PersonnagesService ..> Personnage : <<use>>
@enduml