@startuml
scale 2

class Livre{
    -__id : int
    -__titre : str
    -__isbm : int
    -__auteur :str
}

class LivreDao{
    +find_by_isbm(int) : Livre
    +find_all() : list[Livre]
    +create(Livre) : Livre
}

LivreDao .right.> Livre : <<use>> \n<<create>>

@enduml